apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-neuron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-neuron
  template:
    metadata:
      labels:
        app: llama-neuron
    spec:
      tolerations:
      - key: "aws.amazon.com/neuron"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/instance-type: inf2.xlarge
      initContainers:
      - name: wait-for-template
        image: busybox
        command: ['sh', '-c', 'until [ -f /app/templates/tool_chat_template_llama3.1_json.jinja ]; do echo "Waiting for template file..."; sleep 1; done; echo "Template file found!"']
        volumeMounts:
        - name: chat-template-volume
          mountPath: /app/templates
          readOnly: true
      containers:
      - name: neuron-llm
        image: public.ecr.aws/j4m3t0a6/vllm-neuron
        args:
          - "--host=0.0.0.0"
          - "--port=8080"
          - "--model"
          - "meta-llama/Llama-3.1-8B-Instruct"
          - "--tensor-parallel-size"
          - "2" 
          - "--max-num-seqs"
          - "2"
          - "--max-model-len"
          - "8192"
          - --enable-auto-tool-choice
          - --tool-call-parser=llama3_json
          - --chat-template=/app/templates/tool_chat_template_llama3.1_json.jinja
        volumeMounts:
        - name: chat-template-volume
          mountPath: /app/templates
          readOnly: true
        resources:
          limits:
            cpu: "3"
            memory: "12Gi"
            aws.amazon.com/neuron: "1"
          requests:
            cpu: "3"
            memory: "12Gi"
            aws.amazon.com/neuron: "1"
        ports:
        - containerPort: 8080
        env:
        - name: FI_EFA_FORK_SAFE
          value: "1"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
      volumes:
      - name: chat-template-volume
        configMap:
          name: chat-template
---
apiVersion: v1
kind: Service
metadata:
  name: llama-neuron
spec:
  selector:
    app: llama-neuron
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
